version: "3"

services:
    nodeserver:
        build: ./backend
        links:
            - db
        volumes:
            - "./backend/app:/app"
        ports:
            - "8090:8090"
    db:
        image: mongo
        volumes:
            - "./mongodb/mongod.conf:/etc/mongod.conf"
        ports:
            - "27017:27017"
        command: mongod --config /etc/mongod.conf
    frontend:
        build: ./frontend
        volumes:
            - "./frontend/src:/src"
            - "./backend/app/build:/build"
